### ISSUE TITLE
Xorg Intel Settings & Tearing

### ISSUE THREAD

**Issue by ejmg** [ejmg/an-idiots-guide-to-installing-arch-on-a-lenovo-carbon-x1-gen-6#11]
As discussed [here](https://github.com/ejmg/an-idiots-guide-to-installing-arch-on-a-lenovo-carbon-x1-gen-6/pull/9#issuecomment-419664475) in #9 and onward, there are reports of X1C6 users experiencing tearing in applications like Chrome/ium due to Intel's HD 620 graphics card.

As @mmcdole notes, there is a possible fix in the form of creating an intel conf file with the following content:

```
Section "Device"
        Identifier  "Intel Graphics"
        Driver "intel"
        Option "AccelMethod" "sna"
        Option "TearFree" "true"
        Option "DRI" "3"
EndSection
```

The arch wiki recommends such configs being put in `/etc/X11/xorg.conf.d/20-intel.conf`.

More info on Intel graphics with respect to Xorg can be found in the [arch wiki](https://wiki.archlinux.org/index.php/Intel_graphics#Installation).

**Comment by ejmg** [comment]
One time aside here: the arch intel wiki also talks about other performance enhancing configurations such as Framebuffer compression and Fastboot. Hear anything good about these as tweaks? If so, I can open another issue and add it.

**Comment by mmcdole** [comment]
Spent some further time looking into this tearing issue.

I've been using i3 as my WM and up until now, have had no compositor running.  I fired up [Compton](https://wiki.archlinux.org/index.php/compton) and this completely eliminated the tearing I was seeing while scrolling in browsers.

@ejmg I believe you mentioned in the guide that you use KDE which comes with its own compositor.  This very likely explains the discrepancy between us.

**Comment by ejmg** [comment]
I am thinking of opening a new issue/section of the guide for issues like this because it would be a nice knowledge transfer to have for those who don't want a vanilla DE like KDE to handle these details for them.
