### ISSUE TITLE
Inconsistent Wake from Suspend

### ISSUE THREAD

**Issue by sirusss** [ejmg/an-idiots-guide-to-installing-arch-on-a-lenovo-carbon-x1-gen-6#27]
Thanks for putting this together - I found it really helpful as I installed arch on my X1C5.

I've ran into some issues where my laptop will randomly wake from suspend and I'm having a hard time tracing what's causing this issue (sometimes it's immediate, other times it takes a couple minutes). Wondering if you've ran into a similar problem and what steps you may have taken to solve this.

**Comment by ejmg** [comment]
Hi there! Thanks for the report/question.

Before anything else, given this guide is tailored around the gen 6, I unfortunately cannot guarantee any of my recommendations will work. Furthermore and equally unfortunately, it appears there is no related entry about sleep functionality on the official arch wiki for the x1c5.

With that out of the way, I want to make sure you have looked at the sections concerning the [BIOS upgrade](https://github.com/ejmg/an-idiots-guide-to-installing-arch-on-a-lenovo-carbon-x1-gen-6#bios-update), [hibernation](https://github.com/ejmg/an-idiots-guide-to-installing-arch-on-a-lenovo-carbon-x1-gen-6#hibernate-support), and [sleep](https://github.com/ejmg/an-idiots-guide-to-installing-arch-on-a-lenovo-carbon-x1-gen-6#suspend-support)? I would be surprised if the BIOS upgrade is relevant to you, but the behavior more or less describes the problems experienced by anyone trying to use traditional sleep functionality, i.e. closing the lid to suspend, prior to the Arch community figuring out the patch.

The hibernation section should be applicable regardless of generation and may be worth looking into as well.

If you've already read through the guide in its entirety and read/followed the sections I noted above, then I don't immediately know what could be to blame. I'm current going through finals week and can't put the time to look into it now but please let me know if you do or don't figure this out; I can revisit this in about two weeks and it would be worth documenting the problem somewhere, whether here or on the arch wiki for the x1c5.

**Comment by sirusss** [comment]
Sorry for the delayed response. I never figured out what the issue was and ended up installing gnome (my preferred DE) and removing KDE. Since then, the issue has resolved for me.
