### ISSUE TITLE
Selecting best mirror and more

### ISSUE THREAD

**Issue by Kiwi** [ejmg/an-idiots-guide-to-installing-arch-on-a-lenovo-carbon-x1-gen-6#4]
A close mirror is not always a fast mirror, nor necessarily an up to date mirror. There exists `rankmirrors` which comes with `pacman-contrib` that tests connection speed, and [`reflector`](https://wiki.archlinux.org/index.php/Reflector) which can do more. There is also [archlinux.org/mirrorlist](https://www.archlinux.org/mirrorlist/) which can help with making sure they are up to date and easily filter by region and supported protocols, etc.

A good option is the mirrorlist webapp to get a base list of up to date mirrors and then use `rankmirrors` on that list to get the fastest one for the user.

Would you like me to try to add any of this and also clean up other things and improve it? Or any interest in expanding beyond that specific model to be more generally useful? I don't know org mode but have been looking for a reason to learn it....

The destruction of the beginners installation guide was one of the worst things to happen to arch imo. :(

**Comment by ejmg** [comment]
Thank you for the recs!

I definitely used "closeness" as a heuristic, but also did not make that clear. Do you think it wouldn't be overkill to include `reflector` in the live-usb install session? That's actually what  I did myself but was afraid it would be perceived as "overkill", etc. Let me know what you think!

**Comment by ejmg** [comment]
So I agree that getting the fastest mirror is not the most important thing vs just getting a solid mirror, it's not like Arch is that big anyway lmao.

Do you think just following the wiki hack for sorting mirrors is good enough? I can throw that into the guide: https://wiki.archlinux.org/index.php/mirrors#Sorting_mirrors
